# Generated by Django 2.0.2 on 2018-11-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
