# Generated by Django 2.0.2 on 2018-11-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uprofile',
            options={'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
        migrations.AlterField(
            model_name='uprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
