# Generated by Django 2.0.2 on 2018-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uprofile', '0002_auto_20181116_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uprofile',
            name='nick_name',
            field=models.CharField(blank=True, default='丑八怪', max_length=32, null=True, verbose_name='用户昵称'),
        ),
    ]
