# Generated by Django 2.0.2 on 2018-11-20 15:57

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(choices=[(2, '重磅新闻'), (1, '列表新闻')], db_index=True, default=2, verbose_name='新闻级别')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('image', models.ImageField(upload_to='index/news_images/', verbose_name='新闻图片-展示')),
                ('news_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='新闻时间')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='新闻内容')),
                ('is_delete', models.BooleanField(choices=[(False, '保存'), (True, '删除')], db_index=True, default=False, verbose_name='逻辑删除')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '新闻中心',
                'verbose_name_plural': '新闻中心',
                'db_table': 'NewsCenter',
                'ordering': ('create_at',),
            },
        ),
    ]
