# Generated by Django 2.0.2 on 2018-11-16 10:07

import DjangoUeditor.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('news_time', models.DateTimeField(verbose_name='新闻时间')),
                ('content', DjangoUeditor.models.UEditorField(verbose_name='新闻内容')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='编辑时间')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(choices=[(False, '保存'), (True, '删除')], db_index=True, default=False, verbose_name='逻辑删除')),
                ('create_by', models.ForeignKey(editable=False, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='编辑人')),
            ],
            options={
                'verbose_name': '新闻中心',
                'verbose_name_plural': '新闻中心',
                'db_table': 'NewsCenter',
                'ordering': ('create_at',),
            },
        ),
    ]
