# Generated by Django 2.0.2 on 2018-11-16 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newscenter',
            name='create_by',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
    ]
