# Generated by Django 2.0.2 on 2018-11-20 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_newscenter_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscenter',
            name='create_by',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='编辑人'),
        ),
        migrations.AlterField(
            model_name='newscenter',
            name='news_time',
            field=models.DateTimeField(verbose_name='新闻时间'),
        ),
    ]
