# Generated by Django 2.0.2 on 2018-11-16 16:31

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_newscenter_create_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscenter',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='新闻内容'),
        ),
    ]
