# Generated by Django 2.0.2 on 2018-11-20 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20181120_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newscenter',
            options={'ordering': ('create_time',), 'verbose_name': '新闻中心', 'verbose_name_plural': '新闻中心'},
        ),
        migrations.RenameField(
            model_name='newscenter',
            old_name='create_at',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='newscenter',
            old_name='update_at',
            new_name='update_time',
        ),
    ]
